name: Deploy to App Distribution(Android)

on:
  push:
    branches:
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - name: Cache npm
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-version }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-npm-
      - run: npm install
      - uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-${{ env.cache-version }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-pods-
      - name: Recover release.jks to home directory
        run: echo -n "$RELEASE_JKS_BASE64" | base64 --decode > $HOME/release.jks
        env:
          RELEASE_JKS_BASE64: ${{ secrets.RELEASE_JKS_BASE64 }}
      - name: Recover sentry.properties to android directory
        run: cd android && echo -n "$ANDROID_SENTRY_PROPERTIES_BASE64" | base64 --decode > sentry.properties
        env:
          ANDROID_SENTRY_PROPERTIES_BASE64: ${{ secrets.ANDROID_SENTRY_PROPERTIES_BASE64 }}
      - name: Recover .env to project root directory
        run: echo -n "$DOTENV_BASE64" | base64 --decode > .env
        env:
          DOTENV_BASE64: ${{ secrets.DOTENV_BASE64 }}
      - name: bundle install
        run: cd android && bundle install
      - name: Run Fastlane - Deploy to App Distribution
        run: cd android && bundle exec fastlane internal
        env:
          JSON_KEY_FILE_PATH: ${{ secrets.JSON_KEY_FILE_PATH }}
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
          SIGNING_STORE_FILE: ${{ secrets.SIGNING_STORE_FILE }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD}}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
