name: Deploy Android Canary App

on:
  push:
    branches:
      - canary
    paths:
      - 'android/**'
      - 'src/**'
      - 'proto/**'
      - 'assets/**'
      - 'package.json'
      - 'package-lock.json'

env:
  TZ: 'Asia/Tokyo'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install dependencies
        run: npm ci
      - name: Run bundle install
        working-directory: ./android
        shell: bash
        run: bundle install
      - name: Restore .env.local
        shell: bash
        run: echo "$DOTENV_LOCAL" | tr -d '\r' > ./.env.local
        env:
          DOTENV_LOCAL: ${{ secrets.DOTENV_LOCAL }}
      - name: Restore google-services.json
        shell: bash
        run: echo "$GOOGLE_SERVICES_JSON" | tr -d '\r' > ./android/app/src/dev/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Restore play-store-credentials.json
        shell: bash
        run: echo "$PLAY_STORE_CREDENTIALS_JSON" | tr -d '\r' > ./android/play-store-credentials.json
        env:
          PLAY_STORE_CREDENTIALS_JSON: ${{ secrets.PLAY_STORE_CREDENTIALS_JSON }}
      - name: Restore release.keystore
        shell: bash
        run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > ./android/app/release.keystore
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      - name: Deploy with fastlane
        working-directory: ./android
        shell: bash
        run: bundle exec fastlane deploy_canary
        env:
          JSON_KEY_FILE_PATH: ${{ github.workspace }}/android/play-store-credentials.json
          SIGNING_STORE_FILE: ${{ github.workspace }}/android/app/release.keystore
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          PACKAGE_NAME: me.tinykitten.trainlcd.dev
          ANDROID_HOME: ${{ secrets.ANDROID_HOME }}
