name: Deploy iOS Canary App

on:
  push:
    branches:
      - 'feature/fastlane-ci'
      - '/release.*/'

env:
  cache-version: v1
  TZ: 'Asia/Tokyo'

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - name: bundle install
        working-directory: ./ios
        shell: bash
        run: bundle install
      - name: Deploy with fastlane
        working-directory: ./ios
        shell: bash
        run: bundle exec fastlane deploy_canary
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
