name: Deploy Android Canary App

on:
  push:
    branches:
      - dev
      - feature/self-hosted-runner-android # TODO: マージ前に消す

env:
  TZ: 'Asia/Tokyo'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Initialize id_rsa for Fonts
        env:
          PRIVATE_KEY: ${{ secrets.FONTS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: npm install
      - name: Run bundle install
        working-directory: ./android
        shell: bash
        run: bundle install
      - name: Restore .env.local
        shell: bash
        run: echo "$DOTENV_LOCAL" | tr -d '\r' > ./.env.local
        env:
          DOTENV_LOCAL: ${{ secrets.DOTENV_LOCAL }}
      - name: Restore google-services.json
        shell: bash
        run: echo "$GOOGLE_SERVICES_JSON" | tr -d '\r' > ./android/app/src/dev/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Restore play-store-credentials.json
        shell: bash
        run: echo "$PLAY_STORE_CREDENTIALS_JSON" | tr -d '\r' > ./android/play-store-credentials.json
        env:
          PLAY_STORE_CREDENTIALS_JSON: ${{ secrets.PLAY_STORE_CREDENTIALS_JSON }}
      - name: Restore release.keystore
        shell: bash
        run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > ./android/app/release.keystore
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      - name: Deploy with fastlane
        working-directory: ./android
        shell: bash
        run: bundle exec fastlane deploy_canary
        env:
          JSON_KEY_FILE_PATH: ${{ github.workspace }}/android/play-store-credentials.json
          SIGNING_STORE_FILE: ${{ github.workspace }}/android/app/release.keystore
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          PACKAGE_NAME: me.tinykitten.trainlcd.dev
          ANDROID_HOME: ${{ secrets.ANDROID_HOME }}
