name: ESLint

on:
  push:
    branches:
      - '**'

env:
  cache-version: v1

jobs:
  ci-skip-check:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  lint:
    runs-on: ubuntu-latest
    needs: ci-skip-check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-yarn-
      - run: yarn
      - run: yarn gen:grpc:services
      - run: yarn lint
