name: Jest

on:
  push:
    branches:
      - '**'
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'

env:
  cache-version: v1
  TZ: 'Asia/Tokyo'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        env:
          PRIVATE_KEY: ${{ secrets.FONTS_SSH_KEY }}
        with:
          submodules: recursive
          ssh-key: $PRIVATE_KEY
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest
        run: npm test
