name: Jest

on:
  push:
    branches:
      - '**'
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'

env:
  cache-version: v1
  TZ: 'Asia/Tokyo'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Initialize id_rsa for Fonts
        env:
          PRIVATE_KEY: ${{ secrets.FONTS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest
        run: npm test
