name: Jest

on:
  push:
    branches:
      - '**'

env:
  cache-version: v1
  TZ: 'Asia/Tokyo'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: arduino/setup-protoc@v2
      - run: npm install
      - run: npm test
